version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4001:8081"
    volumes:
      - /app/node_modules
      - .:/app
    restart:  always
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
      volumes:
        - /app/node_modules
        - .:/app
      command: ["npm","run","test"]
